runtime: python39
entrypoint: gunicorn app:app

automatic_scaling:
  max_instances: 1  # Limit to 1 instance
  min_instances: 1  # Ensure 1 instance always runs

instance_class: F1  # Smallest instance type

# service: open-hyper-ai # do not name a service. use the default to avoid creating additional instances
