name: Deploy to GAE

on:
  push:
    branches:
      - dota2bot  # Deploy on pushes to the dota2bot branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: dota2bots
        export_default_credentials: true

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
